### ISSUE TITLE
Are there known official mirrors of mpfun90?

### ISSUE THREAD

**Issue by matthewfeickert** [APN-Pucky/mpfun90#1]
Thanks for making this repository, @APN-Pucky. :+1: I suspect from https://github.com/hep-packaging-coordination/packaging-hep-simulation-stack/issues/3#issuecomment-2496234663 that this is related to your Gentoo packaging work, but it is great to see that someone else was thinking like me with regards to "How to get `mpfun90` when https://www.davidhbailey.com/dhbsoftware/ distributes `mpfun2020`?".

I was wondering, do you know of any "official" mirrors of `mpfun90` or if this repository is basically it? Also, from https://www.davidhbailey.com/dhbsoftware/ (on 2024-11-27) it seems that `mpfun2020` has a modified BSD license (I haven't checked to see how it is modified yet). Do you know if `mpfun90` was licensed under the same license, or did it have a different license?

**Comment by APN-Pucky** [comment]
I did not find mpfun90 anywhere except in the cuttools code, so I put it here with a simple Makefile.
For gentoo/sci's license I just picked BSD, which I realize is probably wrong given that its successor has modified BSD. I was also wondering if mpfun90 code is compatible or can easily be ported to one of the 2020 variants.  I.e. maybe 90 is just the year as a version. Thanks also for the CCed mail.

**Comment by matthewfeickert** [comment]
I think given our email exchanges with DHB we can say "No, there are no official mirrors" and that DHB would like people to stop using MPFUN90 in favor of MPFUN2020.

> For gentoo/sci's license I just picked BSD, which I realize is probably wrong given that its successor has modified BSD. 

Yeah, I think we need to use the DHB license, but as that will get resolved in PR #3 I'll close this issue now.
